# Generated by Django 4.2.7 on 2026-01-19 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание')),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Протяженность (км)')),
                ('estimated_time_h', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)], verbose_name='Примерное время (часы)')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('start_point_lat', models.FloatField(verbose_name='Широта старта')),
                ('start_point_lon', models.FloatField(verbose_name='Долгота старта')),
                ('finish_point_lat', models.FloatField(verbose_name='Широта финиша')),
                ('finish_point_lon', models.FloatField(verbose_name='Долгота финиша')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_hikes', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('weather_summary', models.CharField(max_length=100, verbose_name='Погода')),
                ('weather_temp', models.FloatField(verbose_name='Температура (°C)')),
                ('weather_precipitation', models.FloatField(default=0, verbose_name='Вероятность осадков (%)')),
                ('parking_status', models.CharField(choices=[('available', 'Свободно'), ('limited', 'Ограничено'), ('full', 'Занято'), ('unknown', 'Нет данных')], default='unknown', max_length=20, verbose_name='Статус парковки')),
                ('overall_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Общий балл')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_checks', to='hikes.hikeroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Проверка маршрута',
                'verbose_name_plural': 'Проверки маршрутов',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('coordinates_lat', models.FloatField(verbose_name='Широта')),
                ('coordinates_lon', models.FloatField(verbose_name='Долгота')),
                ('type', models.CharField(choices=[('viewpoint', 'Смотровая площадка'), ('waterfall', 'Водопад'), ('spring', 'Источник'), ('camping', 'Кемпинг'), ('monument', 'Памятник'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип точки')),
                ('routes', models.ManyToManyField(blank=True, related_name='points_of_interest', to='hikes.hikeroute', verbose_name='Маршруты')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hikes.hikeroute', verbose_name='Маршрут')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('route', 'user')},
            },
        ),
    ]
