# Generated by Django 4.2.7 on 2026-01-02 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikeroute',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_hikes', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
    ]
